### ISSUE TITLE
Quelle est la licence de réutilisation de ces données ?

### ISSUE THREAD

**Issue by bzg** [ArchivesNationalesFR/Referentiels#1]
Bonjour, je ne vois pas d'indication de licence de réutilisation de ces données.

Est-ce que la [licence Ouverte 2.0](https://www.etalab.gouv.fr/licence-ouverte-open-licence/) d'Etalab serait appropriée?

PS: Je travaille à Etalab au pôle logiciels libres, mais je peux faire suivre une question aux personnes en charge de l'open data si besoin.

**Comment by florenceclavaud** [comment]
Bonjour @bzg, les Archives nationales diffusent documents et données, lorsque ce sont des informations publiques, sans licence (voir la page [https://www.archives-nationales.culture.gouv.fr/fr/web/guest/reutilisation-des-donnees-publiques](https://www.archives-nationales.culture.gouv.fr/fr/web/guest/reutilisation-des-donnees-publiques). Selon les termes de cette page, le réutilisateur dispose d'un droit non exclusif et gratuit de libre « réutilisation » de ces informations publiques, à des fins commerciales ou non, dans le monde entier et pour une durée illimitée.
C'est donc sous ce même régime que le Lab a placé les référentiels dans l'immédiat, comme indiqué dans le fichier Readme.md à la racine de la release.

**Comment by bzg** [comment]
Merci beaucoup pour cette réponse.  Ces contraintes quant aux réutilisations correspondent à celle de la licence Ouverte 2.0, qui envoie un signal clair à tous les réutilisateurs et qui est la licence recommandée pour les publications en open data du secteur public - mais j'imagine que ce sont des sujets qui ont déjà été considérés de votre côté, et fait l'objet de cette décision.

**Comment by bzg** [comment]
PS: On me souffle que les archives relèveraient du code du patrimoine et non du CRPA, d'où peut-être ce régime de publication distinct.  N'étant pas spécialiste du sujet, je me permets de fermer cette issue moi-même. Merci encore d'avoir pris le temps de me répondre.
